using System.Globalization;
using System.Text;
using PKHeX.Core;

namespace SED.Core;

public static class EmulatorBreakpointExporter
{
    public static string Export(SeedEncounterResult result, string directory)
    {
        Directory.CreateDirectory(directory);
        var species = GameInfo.Strings.Species[result.Pokemon.Species];
        var safeSpecies = string.Concat(species.Select(z => char.IsLetterOrDigit(z) ? z : '_'));
        var game = GetGameCode(result.Pokemon.Version);
        var stem = $"{game.ToLowerInvariant()}_{safeSpecies.ToLowerInvariant()}_frame_{result.Frame}";
        var scriptPath = Path.Combine(directory, $"{stem}.lua");
        var checkpointPath = Path.Combine(directory, $"{stem}_target.ss1");
        var generationPath = Path.Combine(directory, $"{stem}_generation.ss1");
        File.WriteAllText(scriptPath, CreateLua(result, checkpointPath, generationPath), new UTF8Encoding(false));
        return scriptPath;
    }

    public static string CreateLua(SeedEncounterResult result, string checkpointPath, string generationPath)
    {
        var code = GetGameCode(result.Pokemon.Version);
        var species = GameInfo.Strings.Species[result.Pokemon.Species];
        var checkpoint = EscapeLuaPath(checkpointPath);
        var generation = EscapeLuaPath(generationPath);
        return $$"""
            -- Generated by SED for mGBA 0.11 or newer.
            -- Load this through Tools > Scripting before approaching the encounter.
            local expectedCode = "{{code}}"
            local targetState = 0x{{result.State.ToString("X8", CultureInfo.InvariantCulture)}}
            local targetFrame = {{result.Frame}}
            local targetPid = 0x{{result.Pokemon.PID.ToString("X8", CultureInfo.InvariantCulture)}}
            local profiles = {
                BPEE = { seed = 0x03005D80, createMon = 0x08067B4C },
                AXVE = { seed = 0x03004818, createMon = 0x0803A798 },
                AXPE = { seed = 0x03004818, createMon = 0x0803A798 },
                BPRE = { seed = 0x03005000, createMon = 0x0803DA68 },
                BPGE = { seed = 0x03005000, createMon = 0x0803DA68 },
            }

            local code = tostring(emu:getGameCode()):sub(-4)
            local profile = profiles[code]
            if not profile then error("SED breakpoint: unsupported ROM " .. code) end
            if code ~= expectedCode then
                error("SED breakpoint: expected " .. expectedCode .. " but loaded " .. code)
            end

            local targetSeen = false
            local seedWatch
            local generationBreakpoint

            seedWatch = emu:setRangeWatchpoint(function()
                local state = emu:read32(profile.seed) & 0xFFFFFFFF
                if state ~= targetState or targetSeen then return end
                targetSeen = true
                emu:saveStateFile("{{checkpoint}}")
                console:log(string.format("SED target reached: {{species}} frame %d state %08X PID %08X", targetFrame, state, targetPid))
            end, profile.seed, profile.seed + 4, C.WATCHPOINT_TYPE.WRITE_CHANGE)

            generationBreakpoint = emu:setBreakpoint(function()
                if not targetSeen then return end
                emu:saveStateFile("{{generation}}")
                console:log("SED Pokemon generation breakpoint reached and savestate written.")
                emu:clearBreakpoint(seedWatch)
                emu:clearBreakpoint(generationBreakpoint)
            end, profile.createMon)

            if seedWatch < 0 or generationBreakpoint < 0 then
                error("SED breakpoint: this mGBA build could not arm debugger callbacks")
            end
            console:log(string.format("SED armed: {{species}} encounter frame %d state %08X", targetFrame, targetState))
            """;
    }

    private static string GetGameCode(GameVersion version) => version switch
    {
        GameVersion.E => "BPEE",
        GameVersion.R => "AXVE",
        GameVersion.S => "AXPE",
        GameVersion.FR => "BPRE",
        GameVersion.LG => "BPGE",
        _ => throw new NotSupportedException($"No mGBA breakpoint profile is available for {version}."),
    };

    private static string EscapeLuaPath(string path) => path.Replace('\\', '/').Replace("\"", "\\\"");
}
